### ISSUE TITLE
Full control over response headers

### ISSUE THREAD

**Issue by MrVichr** [pallets/quart#140]
I'm writing a facade over an existing web server (pretty much a man-in-the-middle). The response itself seems to work, I've found `make_response` as the low-level function to create a response manually (not sure if there is a better choice):
```python
    resp=await app.make_response((resp_data, resp_status, resp_headers))
    return resp
```
The last problem is with the headers: I noticed that `date` header gets sent twice. One is from my `resp_headers`, which I want to keep as-is. The other I traced to `hypercorn.Config#response_headers`. This creates a `date` header unconditionally, which is then directly added to response headers, without giving me any chance to remove it, or not add it in the first place.

For now, I hacked `quart/app.py` to add `hyperconfig_class` to Quart:
```python
    hyperconfig_class = HyperConfig
```
and change `Quart#run_task`:
```python
        config = self.hyperconfig_class()
        #config = HyperConfig()
```
then in main using
```python
from hypercorn.config import Config as hypercorn_Config
class ConfigWithoutDate(hypercorn_Config):
    def response_headers(self, protocol: str) -> List[Tuple[bytes, bytes]]:
        res=super().response_headers(protocol)
        del res[0]
        return res

Quart.hyperconfig_class=ConfigWithoutDate
app = Quart(__name__)
```
This is obviously not an optimal solution. Can you recommend the easiest way to fully control response headers, including `date` and perhaps also `server`?

**Comment by pgjones** [comment]
The next release of Hypercorn will allow this to be configured, see https://github.com/pgjones/hypercorn/commit/9b16b1b442097eac3b583f1efb7b24279476702a
