### ISSUE TITLE
Quart handling requests "simultaneously"

### ISSUE THREAD

**Issue by GoedendagMC** [pallets/quart#146]
I have a file upload handler, structured as follows (simplified):

```
print('filename= ' + file.filename)
await aiofiles.os.mkdir(filefolder)
print("folder made")
await file.save(os.path.join("/filefolder", filename))
print("file saved")
return '',200
```

The folder path changes depending on a header sent in the request.
Now, when I send several POST requests to upload, instead of handling each of them as would be normal, it groups all the filename prints, then all the foldermade prints, then all the filesaved prints. Is this normal behaviour?

It is problematic, because when multiple files are uploaded at once, it can take a very long time, as they are all run at the same time instead of one (or a few) after another.

Related question: say I hosted this upload handler 10 times, on 10 different URLs, would the performance be better?
If so, is there no way to simulate this from just one file?

I use Hypercorn as ASGI, Nginx reverse proxy after that. 

Thanks in advance!

**Comment by laggardkernel** [comment]
That's how async works ... The file saving is handled in parallel.
