### ISSUE TITLE
Do not attach log handlers if application set up its own handlers

### ISSUE THREAD

**Issue by nirvana-msu** [pallets/quart#153]
Following up on an issue that I recently raised on Gitlab about preventing having Quart's log handlers attached (btw Gitlab issues seem to not be accessible any more?)

Quart certainly behaves differently from Flask w.r.t. log handlers. I've always set up my own handlers early on in Flask, and it never got in the way. Looking at Flask docs, [it says](https://flask.palletsprojects.com/en/2.1.x/logging/#basic-configuration):
> When you want to configure logging for your project, you should do it as soon as possible when the program starts. If [app.logger](https://flask.palletsprojects.com/en/2.1.x/api/#flask.Flask.logger) is accessed before logging is configured, it will add a default handler. If possible, configure logging before creating the application object.

It would be nice if Quart did the same - i.e. do not attach own handlers if there already are some configured by the time application is created.

P.S. Nice seeing development move to GitHub!

**Comment by andrewshadura** [comment]
I agree, the dual logging configuration of Quart/hypercorn forces me to invent ways to work around it, it would be better if it were possible to somehow leave it up to the app.

**Comment by pgjones** [comment]
https://github.com/pallets/quart/commit/a54dab248714f08ff9f49acb32dd47834f86ddc1 Should solve this, I think.

**Comment by nirvana-msu** [comment]
btw @pgjones, huge congrats on Quart becoming a part of Flask family! This is awesome news for Python web framework ecosystem : )  Been hesitating to move off Flask for a while (even though would really prefer asgi) but this makes the choice and switch a no-brainer.

(don't have permissions to post to discord, sorry!)

**Comment by pgjones** [comment]
Thanks, but hiding as off-topic 😛

**Comment by pgjones** [comment]
Fixed in 0.18
