### ISSUE TITLE
Config `from_envvar` doesn't support silent=True properly

### ISSUE THREAD

**Issue by vdurmont** [pallets/quart#154]
Hello,

When I used Flask, I had the following lines of code that would load the config if the env var exists and fail silently if it doesn't.
```python
app = Flask(__name__)
app.config.from_envvar("FLASK_CONFIG", silent=True)
```

I switched to Quart and wrote basically the same thing:
```python
app = Quart(__name__)
app.config.from_envvar("QUART_CONFIG", silent=True)
```
However, this throws an error if `QUART_CONFIG` doesn't exist:
```
E       TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
<path to my venv>/lib/python3.9/site-packages/quart/config.py:197: TypeError
```

Reading the code for `from_envvar`, it is clear that the feature hasn't been ported properly from Flask: https://github.com/pallets/quart/blob/main/src/quart/config.py#L109-L113

Environment:
- Python version: 3.9
- Quart version: 0.17.0

**Comment by pgjones** [comment]
Fixed by 155
