### ISSUE TITLE
JSONIFY_PRETTYPRINT_REGULAR is not working properly

### ISSUE THREAD

**Issue by AsmSafone** [pallets/quart#166]
Its seems like `app.config['JSONIFY_PRETTYPRINT_REGULAR']` is not properly working with quart. It perfectly work with flask. Also there is some more configs option which on flask not in quart, it would be great if you add those configs option.

**I've tried**:
```
from quart import Quart, jsonify

app = Quart(__name__)
app.config['JSONIFY_PRETTYPRINT_REGULAR'] = True

@app.route('/')
async def hello():
    return jsonify({
  "p": {
    "e": {
      "n": {
        "c": "something..."
      }
    }
  }
})

app.run()
```
**Output:**
```
{"p":{"e":{"n":{"c":"something..."}}}}
```
**Expected Result:**
```
{
  "p": {
    "e": {
      "n": {
        "c": "something..."
      }
    }
  }
}
```

**Environment**:

- Python version: 3.9.10
- Quart version: 0.18.0

**Comment by pgjones** [comment]
It is no longer used, instead the JSONProvider itself can be customised, see [docs](https://quart.palletsprojects.com/en/latest/how_to_guides/json_encoding.html).

**Comment by AsmSafone** [comment]
> It is no longer used, instead the JSONProvider itself can be customised, see [docs](https://quart.palletsprojects.com/en/latest/how_to_guides/json_encoding.html).

in that way, i've to change/customize every jsonify response ig. what if i wanna do the `JSONIFY_PRETTYPRINT_REGULAR` for all, wen the client init?

**Comment by AsmSafone** [comment]
> Just wondering, what's your usecase for prettyprinting it in the first place? Computers don't care, and humans can use a browser that prettyprints (firefox does it by default, chrome maybe too) or a client that prettyprints (e.g. httpie) or pipe through a tool like `jq`...

ik, but every browsers don't prettyprint by default (even chrome also). It looks cool or easy to read dict items if in prettyprinted (by default) for humans. nvm um not taking about computer.

**Comment by ThiefMaster** [comment]
IMHO it doesn't look good to have pretty-printed json that's not syntax-colored ;)

**Comment by AsmSafone** [comment]
> 

nvm, so all flask configs or option not in quart? quart !=flask?

**Comment by AsmSafone** [comment]
> IMHO it doesn't look good to have pretty-printed json that's not syntax-colored ;) so maybe time to install a chrome extension it it really doesn't prettyprint it by default (wtf)

nvm, so all flask configs or option not in quart? quart !=flask?
