### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by smfelsher** [pallets/quart#185]
I'm following the tutorial on [YouTube](https://youtu.be/0aCHKGRJgUc) and the hot-reload feature is not working for me. I didn't make it any further than 2:29 in the video.

I expected my terminal to re-display the start-up messages, but it behaved as if it did not detect the file change.

Environment:

- Python version: 3.10.6
- Quart version: 0.18.0
- Pipenv version: 2022.8.24
- VSCode: 1.71.2
- OS: Linux x64 5.19.7-1-MANJARO

**Comment by davidism** [comment]
Please use [GitHub Discsussions](https://github.com/pallets/quart/discussions) for questions about your own code. This tracker is for issues related to the project itself. Be sure to include a minimal, complete, and verifiable example demonstrating your issue.

**Comment by smfelsher** [comment]
How is this a problem with my code?

**Comment by Vivanov98** [comment]
Can confirm I am getting the same behaviour on ubuntu 20.04.1

Running hypercorn directly seems to work though
`hypercorn app_module:app --reload`

**Comment by davidism** [comment]
It's a video tutorial, there's nothing that can be fixed about that. I suggest posting further in the Q&A if you think you have a diagnostic or answer to the issue.

**Comment by pgjones** [comment]
This one is actually a bug. The latest Hypercorn has a much better (is now cross platform reliable) reloading system, however it breaks Quart's usage. As a workaround use Hypercorn 0.13.2 until this is fixed in Quart.

**Comment by pgjones** [comment]
Fixed in 7634a5a56b757eb6c5602407114d587ace8f5590

**Comment by Vivanov98** [comment]
Thanks!
