### ISSUE TITLE
Same version for extensions supported py pallets

### ISSUE THREAD

**Issue by albcunha** [pallets/quart#188]
Some other projects keep the same versions for all extensions, such as https://github.com/strapi/strapi, and I find that very intuitive to update all packages and check if everything is updated.

Maybe this can be considered?

**Comment by davidism** [comment]
It's not really clear what you mean, but we don't plan to change how dependencies work .

**Comment by albcunha** [comment]
Instead of:
quart==0.18.0
quart-auth==0.7.0
quart-schema==0.13.0
Quart-Session==1.0.4
quart-openapi==1.7.2
quart-Rapidoc==0.5.1

we would have:

quart==1.72
quart-auth==1.72
quart-schema==1.72
Quart-Session==1.72
quart-openapi==1.72
quart-Rapidoc==1.72

I realize now that quart still is on 0.18 while some extensions are on 1.72, but maybe they could "wait", such as 1.72.1,1.72.2, etfc...?

**Comment by davidism** [comment]
We're not a monorepo, extensions aren't necessarily maintained by the same people, and extensions don't necessarily require new releases every time anything else is released.
