### ISSUE TITLE
Is 0.18 the prerelease?

### ISSUE THREAD

**Issue by LukeMarlin** [pallets/quart#190]
Sorry to use this space for a question, but I cannot access discord ("invite is invalid", might be due to browser checks) and it doesn't really belong to SO either.

Basically, in a comment here https://github.com/pallets/quart/issues/156#issuecomment-1179691917 @pgjones mentioned that next release would be  "in effect" a prerelease before v1. Since 0.18.0 was published after that comment, I'd like to know if indeed, you are headed towards a 1.0 in the near future, and if 0.18.0 can be considered a somewhat stable prerelease.

Note that my goal isn't to be pushy here, I'm just trying to gather some info to plan for a migration from flask to quart properly!

**Comment by davidism** [comment]
It is fine to migrate to it now, no need to wait. We don't promise any specific time for releases.

**Comment by LukeMarlin** [comment]
Thank you for confirming!

Side note: the link itself is probably fine, but discord seems picky and reports invalid invites if it does not like your browser setup/ip/whatever, so it's definitely not a general issue. Just be aware that it's not available for everyone :)
