### ISSUE TITLE
NotImplementedError on loop.add_signal_handler

### ISSUE THREAD

**Issue by Mindiell** [pallets/quart#193]
Description : using the sample code from readme on Windows makes the appliction crash with : 
NotImplementedError on asyncio\events.py, line 53, in add_signal_handler

It should fail silently for SIGINT and SIGTERM (which are the Unix signals), but should not for SIGBREAK (which is the Windows signal)

Environment:

- Python version: 3.10.7
- Quart version: 0.18.2

I'll propose a fix quickly for this.

**Comment by OttomanZ** [comment]
Same issue here.

**Comment by pgjones** [comment]
Fixed in 68da65c9da6f6efe2327c2db2154e88f6297085b
