### ISSUE TITLE
send_file taking bytes to send as-is

### ISSUE THREAD

**Issue by yan-hic** [pallets/quart#203]
Simple enhancement request so one does not need to wrap in `io.Bytes()`... (_as I keep forgetting)_

As per https://quart.palletsprojects.com/en/latest/reference/source/quart.helpers.html#quart.helpers.send_file, the current acceptance of `bytes` as valid type for `filename_io` is misleading as a filename would always be string, no ?

It would be best to repurpose the `bytes` input as the body to send in the response (wrapping in `io.Bytes()` behind the scenes)

**Comment by davidism** [comment]
Check the Python docs about paths, paths can be strings or bytes.
