### ISSUE TITLE
How to validate a form?

### ISSUE THREAD

**Issue by Nicolas-M15** [pallets/quart#210]
In Quart, how can I validate a form on submit?

The Flask equivalent is: 

```
form = SignInForm()
    
next = request.args.get('next')
    
if request.method == "POST":
        if form.validate_on_submit():

```
I have the following error:
`RuntimeWarning: coroutine 'QuartForm.validate_on_submit' was never awaited`

Environment:

- Python version: 3.8
- Quart version: 0.18.3

**Comment by pgjones** [comment]
I'm not sure what extension you are using, but `if await form.validate_on_submit()` may work given the error.
