### ISSUE TITLE
quart.flask_patch does not work for Flask-Assets

### ISSUE THREAD

**Issue by cajual** [pallets/quart#214]
# The Issue

```
Traceback (most recent call last):
  File "/Users/.../serve.py", line 1, in <module>
    from app import create_app
  File "/Users/.../app/__init__.py", line 9, in <module>
    from app.assets import assets
  File "/Users/.../app/assets.py", line 1, in <module>
    from flask_assets import Bundle, Environment, Filter
  File "/Users/.../.venv/lib/python3.11/site-packages/flask_assets.py", line 8, in <module>
    from flask import _request_ctx_stack, current_app
ImportError: cannot import name '_request_ctx_stack' from 'quart.flask_patch'
```

# How to Reproduce:

Add `import quart.flask_patch` to the top of the document before loading assets.

# Expected Behavior:

The flask patch would allow Flask-Assets to extend Quart with WebAssets bundles.

# Environment:

- Python version: ^3.11
- Quart version: ^0.18.3

**Comment by cajual** [comment]
These changes fix this specific issue:
https://github.com/miracle2k/flask-assets/pull/155/files

**Comment by pgjones** [comment]
Looks like this is being worked on in Flask-Assets
