### ISSUE TITLE
Documentation/Example error: Middleware return

### ISSUE THREAD

**Issue by Samonitari** [pallets/quart#217]
Thanks for the awesome project!

There is actually two things with the [middleware example](https://quart.palletsprojects.com/en/latest/how_to_guides/middleware.html):
- It returns `401`, but according to code `401` spec: "The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource." I think `403` would be the correct return code...
- I had a hard time replacing the `error_response` function with something more succinct, like returning a `quart.Response`. I ultimately gave up, last error was from werkzeug missing app context. Maybe it is a bad pattern to include quart in a separate, quite standalone class's probably separate file.
But generally it could be better with some type annotations about `app`, `scope`, `receive`, `send`, about which the reader is quite lost.

**Comment by pgjones** [comment]
The only constraint on the `app` is that is be a ASGI framework (it need not be Quart at all). Are you sure middleware is the best solution for your problem?

**Comment by Samonitari** [comment]
> Are you sure middleware is the best solution for your problem?

Thanks for the reply!
I needed **exactly** the same `X-Secret` stuff, which is better handled there than in the app, as latter uses Quart-Schema, and this way I can make request **don't** reach validation wo. proper header.
BTW, in the example the strings shouldn't be compared to `b'<value>'` (bytestrings)? At least that's how it works for me...

**Comment by pgjones** [comment]
Thanks, I've improved the docs in c60d3f7181a9632a96f6ffb6f1d4add09eaff20c

Btw I still think a decorator makes more sense here, as you can prevent the request reaching validation by placing the authentication decorator before the validation one.
