### ISSUE TITLE
App context not shared via pytest fixtures

### ISSUE THREAD

**Issue by GENL** [pallets/quart#222]
Hi, I wonder why the quart's app context cannot be shared via fixtures. 

```python
@pytest.fixture
async def app_context(app): # app is a quart instance
    async with app.app_context() as app_context:
          await async_call() # All good: context is available here:
          yield app_context


async def test_smth(app_context):
    await async_call() # Error: not within an app context
```

We would expect the test to be running normally at the `yield`, but it doesn't like the context is lost. I'm I missing something or at least can this behavior be explained to me, please? Could it be a bug in the async-io level itself?

Thank you :pray: 

Environment:

- Python version: 3.9
- Quart version: 0.18.3

**Comment by davidism** [comment]
An app context should not be pushed for an entire test, do not do `with app.app_context(): yield` in a fixture. Only push a context manually very locally to where that's needed.

**Comment by larsblumberg** [comment]
@davidism I'd really like to know the technical reason why trying to provide an app context via fixture won't work. As @GENL  describes above, if one tries yielding the app context from a fixture, `current_app` wouldn't "resolve" it in the actual test using the fixture. Could you please point us to resources which explain why this is the technically the case?

**Comment by davidism** [comment]
* https://flask.palletsprojects.com/en/2.2.x/appcontext/
* https://flask.palletsprojects.com/en/2.2.x/lifecycle/#how-a-request-is-handled
* https://github.com/pallets/flask/blob/7ed89d3f9d2207c9a607f5dcdce106c0278e1332/src/flask/ctx.py#L357-L365

**Comment by larsblumberg** [comment]
> I'm not entirely sure what you're trying to say, but I'm not clear why you think that either. The context is active as long as the with block hasn't ended, and yielding suspends a function, it doesn't end it.

Sorry for my poor wording. I was referring to the example in the OP:

```
@pytest.fixture
async def app_context(app): # app is a quart instance
    async with app.app_context() as app_context:
          await async_call() # All good: context is available here:
          yield app_context


async def test_smth(app_context):
    await async_call() # raises exception: not within an app context
```

The moment `yield app_context` is executed and flow control is given to `test_smth()`, the app context is no longer available. An exception is raised by `quart` saying that we are not within an app context. And that is despite the `yield app_context` being executed within `async with app.app_context() as app_context:`. Maybe this is a particularity to the way how async tests are executed by `pytest`?
