### ISSUE TITLE
Quart::send_from_directory produces ( semanticly ) incorrect response object in case of 304 response

### ISSUE THREAD

**Issue by SamCoutteauHybrid** [pallets/quart#223]
**Bug**

When serving files from a directory using `send_from_directory`, Quart sometimes returns an `304 Not Modified` response.
However the content in this response is not empty as it should be as dictated by RFC 7230

> Any response to a HEAD request and any response with a 1xx
       (Informational), 204 (No Content), or 304 (Not Modified) status
       code is always terminated by the first empty line after the
       header fields, regardless of the header fields present in the
       message, and thus cannot contain a message body.
       https://www.rfc-editor.org/rfc/rfc7230#section-3.3.3
 
This can cause issues with certain ASGI web servers such as uvicorn, which rely on h11 ( https://github.com/tiangolo/fastapi/issues/2253#issuecomment-717357627 ).

**Replication**

```python
from quart import Quart, send_from_directory

app = Quart(__name__)

@app.route("/<path:path>", methods=[ 'GET' ])
async def serve_static( path ):
    response = await send_from_directory( "public" , path )
    print( ( response.content_length ) )
    print( len( data ) )
    return response
```
Launch this application using any prefered method and request a none empty file located in `./public` until it returns a 304 and observe that both `content_length` and the actual data are not empty

**Expected behavior**

```python
from quart import Quart, send_from_directory

app = Quart(__name__)

@app.route("/<path:path>", methods=[ 'GET' ])
async def serve_static( path ):
    response = await send_from_directory( "public" , path )
    response.set_data( b"" )
    return response
```

Manually setting the data to no bytes corrects the bug.

Environment:

- Python version: 3.10.4
- Quart version: 0.18.3

**Comment by pgjones** [comment]
Thanks, fixed with [36fadd8](https://github.com/pallets/quart/commit/36fadd84e20d3aee08962b7a0608999f0b4c33a9)
