### ISSUE TITLE
Add 'text' parameter to config.from_file as it was added to Flask

### ISSUE THREAD

**Issue by kuba-baku** [pallets/quart#226]
Please add 'text' parameter to config.from_file, as it was added to Flask in [https://github.com/pallets/flask/commit/b10b6d4af1127fdfb0a74221af0c020ced71fece](https://github.com/pallets/flask/commit/b10b6d4af1127fdfb0a74221af0c020ced71fece)

Without this parameter we can't use Python's 3.11 Standard library tomllib.load, e.g. `app.config.from_file("config.toml", load=tomllib.load)` because it fails on

> File "/app/.venv/lib/python3.11/site-packages/quart/config.py", line 270, in from_file
>     data = load(file_)
>            ^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/tomllib/_parser.py", line 63, in load
>     raise TypeError(
> TypeError: File must be opened in binary mode, e.g. use `open('foo.toml', 'rb')`

**Comment by pgjones** [comment]
Fixed in 4afdb8802a33172ad5b7f981007b432fbc1311bb
