### ISSUE TITLE
Missing compatibility symbols

### ISSUE THREAD

**Issue by kdienes** [pallets/quart#236]
The Flask compatibility symbols are missing a few symbols:

File "/usr/lib/python3/dist-packages/flask_openapi3/commands.py", line 7, in <module>
    from flask.cli import click
ImportError: cannot import name 'click' from 'quart.flask_patch.cli' (/usr/lib/python3/dist-packages/quart/flask_patch/cli.py)

and:

File "/usr/lib/python3/dist-packages/flask_admin/helpers.py", line 160, in get_redirect_target
    target = request.values.get(param_name)
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'get'

Environment:

$ python3 --version
Python 3.11.2

$ dpkg -l | grep python3-quart
ii  python3-quart                                    0.18.3-2                            all          Python ASGI web microframework with the same API as Flask

**Comment by pgjones** [comment]
Please open on https://github.com/pgjones/quart-flask-patch if this is a problem still (I think I fixed it)
