### ISSUE TITLE
Dependency Issue. `quart 0.18.4 requires blinker<1.6, but you have blinker 1.6.2 which is incompatible.` but flask requires blinker 1.6.2

### ISSUE THREAD

**Issue by collinsmarra** [pallets/quart#247]
Environment:

- Python version: 3.9.2
- Quart version: 0.18.4
- Flask Version: 2.3.2

**Comment by davidism** [comment]
This is addressed by c9b555ff284bb54a45adab44c8e6d78ab8713da0, which is not released yet.
