### ISSUE TITLE
test_app does not have a config object

### ISSUE THREAD

**Issue by HelgeKrueger** [pallets/quart#251]
I'm using the async with app.test_app() to ensure that the before_serving and so on routines are run to run functional tests. Unfortunately, it seems that the config object is not added to the test app and thus needs to be added manually, i.e. with the workaround:

```
 async with app.test_app() as my_test_app:
     my_test_app.config = app.config
```

This seems like a bug, as my before_serving routines populate app.config.

Minimal example:

```
import asyncio
from quart import Quart

app = Quart(__name__)

print(app.config)


async def test():
    async with app.test_app() as my_test_app:
        print(my_test_app)
        print(my_test_app.config)


asyncio.run(test())
```
crashes with output

```
<Config {'APPLICATION_ROOT': None,  .... >
<quart.testing.app.TestApp object at 0x7f985e30b430>
...
AttributeError: 'TestApp' object has no attribute 'config'
```

Environment:

- Python version: 3.10
- Quart version: 0.18.4

**Comment by davidism** [comment]
The test _client_ is not the same as the app, it wouldn't have the same attributes or methods. You still have the app, access it directly.

**Comment by davidism** [comment]
The test app object is documented as being for ensuring lifecycle and background tasks complete. https://quart.palletsprojects.com/en/latest/how_to_guides/background_tasks.html#testing-background-tasks It's not intended as a proxy to the actual app.

**Comment by HelgeKrueger** [comment]
Ok, I understand what to do then. Using 

```
@pytest.fixture
async def test_app()
  await app.startup()
  yield app
  await app.shutdown()
```

yields a test_app that has undergone startup / shutdown.
