### ISSUE TITLE
CI and test suite are failing

### ISSUE THREAD

**Issue by kurtmckee** [pallets/quart#253]
The test suite is currently failing, both locally and in CI ([recent example against `main`](https://github.com/pallets/quart/actions/runs/5564594450/jobs/10164283497)).

```
____________________ ERROR collecting tests/test_config.py _____________________
ImportError while importing test module '/home/runner/work/quart/quart/tests/test_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_config.py:8: in <module>
    import toml
E   ModuleNotFoundError: No module named 'toml'
```

Environment:

- Python version: All tested Python versions
- Quart version: Latest code on `main` branch

**Comment by pgjones** [comment]
Yes, I have a branch I'm working on to use Flask's (config) code that will fix this. It is more difficult to complete than I anticipated.

**Comment by kurtmckee** [comment]
Okay, glad I got filed this issue prior to starting work on this. 😀

If you'd like a second pair of eyes on this, push the branch and ping me in a PR! 👍

**Comment by kurtmckee** [comment]
I've created PRs that individually address various issues.

* #254 fixes the ImportError happening due to a missing `toml` dependency
* #255 fixes some pre-commit failures

Taken together, these fix almost all of the issues that I found. The only remaining issue is a mypy typing issue involving a Protocol, and I'll leave that for someone else to address.

**Comment by pgjones** [comment]
Fixed, thanks for your help.
