### ISSUE TITLE
pyright infers incorrect type for Quart.instance_path

### ISSUE THREAD

**Issue by eddieantonio** [pallets/quart#257]
[Pyright](https://github.com/microsoft/pyright), the static type checker used by the [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) VS Code extension will infer the incorrect type for `Quart.instance_path`.

Example:

```python
from quart import Quart
app = Quart(__name__)

reveal_type(app.instance_path)
```

**Pyright output**:

```
/Users/eddie/Programming/quart/example.py
  /Users/eddie/Programming/quart/example.py:4:13 - information: Type of "app.instance_path" is "str | None"
0 errors, 0 warnings, 1 information 
```

The type should be inferred to be `pathlib.Path`.

Note that mypy, with [`--allow-redefinition`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-allow-redefinition) is able to infer the type correctly:

**mypy output**:

```
example.py:4: note: Revealed type is "pathlib.Path"
Success: no issues found in 1 source file
```

A straightforward way to fix this is to remove the redefinition in `app.py`:

https://github.com/pallets/quart/blob/206d93f74846fd697650bf85ef1de36c86716d48/src/quart/app.py#L294

I think changing the source code is more scalable than requiring all developers change the configuration of whatever new, hip static type-checker people are using 😅 

Environment:

- Python version: Python 3.11.4
- Quart version: 0.18.4, but still present in HEAD (commit 206d93f74846fd697650bf85ef1de36c86716d48)
- pyright version: 1.1.320
- mypy version: 1.4.1

**Comment by davidism** [comment]
Happy to review a PR.

**Comment by eddieantonio** [comment]
Closing because HEAD (29f68ce2f2a2a8e59381351a8cfae152597718c4) now has a consistent type inferred for `instance_path` in both mypy and pyright.

Pyright output:

```
/Users/eddie/Programming/quart/example.py
  /Users/eddie/Programming/quart/example.py:4:13 - information: Type of "app.instance_path" is "str"
0 errors, 0 warnings, 1 information
```

Mypy output: 

```
example.py:4: note: Revealed type is "builtins.str"
Success: no issues found in 1 source file
```

---

The type has **changed** from `pathlib.Path` to `str`, which is a ❗❗❗ **breaking change** ❗❗❗  for the next release.
