### ISSUE TITLE
`quart.redirect` documentation and source code mismatch

### ISSUE THREAD

**Issue by fabge** [pallets/quart#262]
The documentation says that [`quart.redirect`](https://pgjones.gitlab.io/quart/reference/source/quart.html?highlight=redirect#quart.redirect) has 3 parameters:

- location – the location the response should redirect to.
- code – the redirect status code. defaults to 302.
- Response (class) – a Response class to use when instantiating a response. The default is werkzeug.wrappers.Response if unspecified.

However, when [inspecting the source code](https://github.com/pallets/quart/blob/4bba6b4bb00600283e8eb2d264a22ca3037784cf/src/quart/helpers.py#L401C4-L401C4), this does not seem to be true:

```python
def redirect(location: str, code: int = 302) -> WerkzeugResponse:
    """Redirect to the location with the status code."""
    if current_app:
        return current_app.redirect(location, code=code)

    return werkzeug_redirect(location, code=code)
```

**Comment by muddi900** [comment]
These are the old versions of docs. This is the current version: https://quart.palletsprojects.com/en/latest/reference/source/quart.helpers.html#quart.helpers.redirect

**Comment by fabge** [comment]
sorry for that, thanks!
