### ISSUE TITLE
request.url points to the wrong location when ASGI root_path is set

### ISSUE THREAD

**Issue by heuripedes** [pallets/quart#264]
`request.url` points to the wrong location when ASGI `root_path` is set.

**Code to reproduce**
```python
# save as app.py
from quart import Quart, url_for, request

app = Quart(__name__)

@app.get("/")
def index():
    return f"""<pre>
url_for("index"): "{url_for("index")}"
url_for("index", _external=True): "{url_for("index", _external=True)}"

request.url: "{request.url}"
request.path: "{request.path}"
request.root_path: "{request.root_path}"
"""

if __name__ == "__main__":
    def with_root_path(asgi_app, root_path):
        async def middleware(scope, receive, send):
            scope["root_path"] = root_path
            return await asgi_app(scope, receive, send)

        return middleware

    app.asgi_app = with_root_path(app.asgi_app, "/app")
    app.run()
```

**How to reproduce**
1. Run one of the following commands and open http://127.0.0.1:5000/app:
    * `python ./app.py`
    * `hypercorn --bind=:5000 --root-path /app app.py`
    * `uvicorn --port 5000 --root-path /app app:app`
2. Notice how `request.url` points to `http://127.0.0.1:5000/app/app/` rather than `http://127.0.0.1:5000/app/`

![image](https://github.com/pallets/quart/assets/59172/cc373737-ebe9-47cd-83cd-4e6715be3fbd)

**Expected behavior**
* `request.url` should be pointing to `http://127.0.0.1:5000/app/`
* `request.path` should be either `"/"` or `""`

Environment:

- Python version: 3.9.17
- Quart version: 0.18.4

**Comment by pgjones** [comment]
Thank you this is a really helpful bug report. Fixed in 7be545c4e2dbd170643a7db19ac4a841df0ca87a
