### ISSUE TITLE
dont know how to get multiple entries in formdata using request.files 

### ISSUE THREAD

**Issue by alexissinglaire** [pallets/quart#270]
Environment:

- Python version: 3.11.4
- Quart version: 0.18.4

**Comment by davidism** [comment]
```
request.files.getlist
```

**Comment by alexissinglaire** [comment]
> ```
> request.files.getlist(key)
> ```

i tried before and it's not recognize the getlist.

**Comment by alexissinglaire** [comment]
this is the error when i use the getlist

AttributeError: 'coroutine' object has no attribute 'getlist'

**Comment by davidism** [comment]
```python
files = await request.files
files.getlist(key)
```

https://quart.palletsprojects.com/en/latest/how_to_guides/flask_migration.html#async-and-await
