### ISSUE TITLE
request.files.getlist(key) encountered error AttributeError: 'coroutine' object has no attribute 'getlist'

### ISSUE THREAD

**Issue by alexissinglaire** [pallets/quart#271]
Environment:

- Python version: 3.11.4
- Quart version: 0.18.4

**Comment by alexissinglaire** [comment]
Why you closed this issue ? As i explained the getlist is not known.

**Comment by ThiefMaster** [comment]
you may need to await the access to `request.files` before being able to call a method on it. also, why open a second issue instead of continuing in #270?
