### ISSUE TITLE
KeyError: EXPLAIN_TEMPLATE_LOADING

### ISSUE THREAD

**Issue by pamelafox** [pallets/quart#280]
I get a KeyError 'EXPLAIN_TEMPLATE_LOADING' when trying to update a Quart app to latest 0.19.2 version.

This is the app I was trying to update:
https://github.com/Azure-Samples/chatgpt-quickstart
I've pinned it to 0.18 for now.

I believe that's due to Quart being more closely related to Flask now, but Quart failing to provide a default for EXPLAIN_TEMPLATE_LOADING

https://github.com/pallets/flask/blob/14232513fd618be02e0ab4b223f3105fcdde3cfe/src/flask/app.py#L194 https://github.com/pallets/quart/blob/d4fec2a035a82bd068e1bc83690197d4696ed322/src/quart/app.py#L232

Environment:

- Python version: 3.11.5
- Quart version: 0.19.2

**Comment by suchgpg** [comment]
Having the same issue,
Adding `app.config['EXPLAIN_TEMPLATE_LOADING'] = True` seemed to fix the issue, but it is still monkey patching...

**Comment by pgjones** [comment]
Thanks, fixed in [400d72a](https://github.com/pallets/quart/commit/400d72ad3d11cc5e6f5b2a411c9b4036529be526)

**Comment by martinbndr** [comment]
> Thanks, fixed in [400d72a](https://github.com/pallets/quart/commit/400d72ad3d11cc5e6f5b2a411c9b4036529be526)

Thank you :D Will this be updated at pypi in a short period of time or will you put some other fixes/updates before pushing?

**Comment by pgjones** [comment]
0.19.3 is released.
