### ISSUE TITLE
`get_template_attribute` is not available in async mode

### ISSUE THREAD

**Issue by mattgiles** [pallets/quart#290]
I am porting a Flask app to Quart for websockets support and it's going pretty smoothly!

However, it would be convenient for my new websockets handler to be able to return a chunk of rendered html which is encapsulated in a jinja macro--so that in other contexts my full blown html templates can use the same code to render the same component consistently.

Is there another way to ask a websockets handler to return a rendered macro, other than by using `get_template_attribute`? If not, it seems this Flask helper is not really supported in Quart.

**Comment by davidism** [comment]
There's nothing async about this method, so you can import it from Flask. All the function does is load the template, access its compiled module, and get the requested attribute on it. You could just do that directly too: `app.jinja_env.get_tempmlate(template_name).module.attribute_name`.
