### ISSUE TITLE
Add support mount other ASGI applications

### ISSUE THREAD

**Issue by evgenii-moriakhin** [pallets/quart#293]
Hi
I would like to know if the ability to mount other ASGI applications in Quart exists or has been rejected?  Like Starlette, Litestar and Black Sheep for example allow this (e.g. https://www.neoteroi.dev/blacksheep/mounting/).
I didn't find it in the source code or documentation

**Comment by pgjones** [comment]
It is unlikely to be supported as I think this doesn't belong in the framework. Instead I'd recommend some dispatcher middleware, such as [hypercorn's](https://hypercorn.readthedocs.io/en/latest/how_to_guides/dispatch_apps.html).
