### ISSUE TITLE
Remove poetry from examples in documentation

### ISSUE THREAD

**Issue by n1ngu** [pallets/quart#321]
Documentation is way too biased towards setting a development environment with poetry.

I think docs should be agnostic to the packaging / venv manager the user should use. Otherwise documentation has many preambles devoted to setting up tooling unrelated to `quart` and can confuse inexpert python users into installing things they don't actually need.

**Comment by davidism** [comment]
We need to pick something. We may choose to use another tool in the future, but I don't think it's particularly pressing to change. I don't personally use Poetry, but I'm sure Poetry users would take issue with "confuse inexpert python users into installing things they don't actually need". 😉

**Comment by n1ngu** [comment]
Sure, no pressing thing to change. Just wondering whether a community contribution regarding this would be welcome or not.

> We need to pick something.

I think `pip install quart` and `[python -m] quart -A mymodule:app` or a final `if __name__ == "__main__": app.run()` in the examples would be much more straightforward for everybody. Then again users of a particular packaging system can set an alias/entrypoint with their favorite flavor.

IMHO poetry fellows will understand that pointing users to write
```
[tool.poetry.scripts]
start = "mymodule:run"
```
in their pyproject.toml when they might not be using poetry can lead to frustration and a waste of time for the people unaware of the intricate entrypoint ecosystem.

Also, it is odd that the first three sections of each `quart` example are about setting up a poetry development environment. I think the docs would benefit from reducing duplication and just linking to the existing [quickstart](https://quart.palletsprojects.com/en/latest/tutorials/quickstart.html) page. Maybe _that_ would be the place were the docs could show examples about how to setup better app layouts for various venv managers/packaging systems.
