### ISSUE TITLE
New doc contribution: Add a doc to integrate Quart with BentoML

### ISSUE THREAD

**Issue by Sherlock113** [pallets/quart#330]
Hi Quart community,

I would like to add a doc to explain how to integrate Quart with BentoML, an open-source model serving framework. Mounting Quart on a BentoML Service can help extend machine learning services with additional web functionalities, such as custom APIs for data processing, user management, or serving static files and web user interfaces, which are not directly related to model serving.

This doc can be similar like this one https://docs.bentoml.com/en/latest/guides/asgi.html#quart.

@pgjones Could you please tell me where is the best place to add this doc?

Thanks!

**Comment by davidism** [comment]
Thanks, however we don't typically add more services to the docs. You're welcome to host instruction in your own docs.
