### ISSUE TITLE
Background tasks can disappear mid-execution

### ISSUE THREAD

**Issue by jakubsvehla** [pallets/quart#339]
According to the `asyncio` documentation, [it is necessary to keep a strong reference to a task to avoid it disappearing mid-execution because the event loop only keeps weak references to tasks](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task). However, Quart uses a `WeakSet` to store the tasks which means that they can potentially be garbage collected before they finish. And users cannot keep their own strong references because the task is not returned.

The solution would be to use normal `set` instead of the `WeakSet` to keep the tasks in the `background_tasks` app instance variable and add `task.add_done_callback(self.background_tasks.discard)` to the `add_background_task` method after the task is created.

I tried to reproduce the bug but wasn't able to. I found several discussions where others are also not able to reproduce this behavior but nevertheless it's still recommended (both in the official docs and in the discussions) to keep the strong references (and use a callback to remove it) because it can happen in some cases that the task disappears before finishing.

Here are some discussions related to that:

- https://stackoverflow.com/questions/71938799/python-asyncio-create-task-really-need-to-keep-a-reference
- https://github.com/python/cpython/issues/88831
- https://github.com/python/cpython/issues/91887
- https://github.com/python/cpython/issues/117379

I can also create a merge request for it but I won't be able to create a failing test for it since I wasn't able to reproduce it.

Environment:

- Python version: 3.12
- Quart version: 0.19.5

**Comment by pgjones** [comment]
Thanks, fixed in 425f685d213f8c3d464d1ce4e347ccf36e609330
