### ISSUE TITLE
Coroutine not awaited

### ISSUE THREAD

**Issue by Kaki-In** [pallets/quart#355]
I am using quart and getting a few errors sometimes. After reading them more, I got that : 

```
/usr/local/lib/python3.10/dist-packages/quart/ctx.py:141: RuntimeWarning: coroutine 'TCPServer._idle_timeout' was never awaited
  await super()._push_appctx(_cv_request.set(self))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

To replicate, simply deploy a quart server, maybe using cookies and post. 

Expected behavior : Work successfully, and not write any error if it successed. And also be translated perfectly to asyncio. 

Environment:

- Python version: python3.10
- Quart version: latest (installed via pip today, 4th of September 2024)

**Comment by davidism** [comment]
Please provide a minimal reproducible example. "Run a server, maybe do something" is not enough.

**Comment by Kaki-In** [comment]
I am not sure what is exactly doing this issue. 

All I know is, that when I use the "GET" method everything is fine, but everytime I use the "POST" method I obtain this kind of messages : 

```
Task exception was never retrieved
future: <Task finished name='Task-49' coro=<ASGIHTTPConnection.handle_request() done, defined at /usr/local/lib/python3.10/dist-packages/quart/asgi.py:96> exception=RuntimeError('TaskGroup <TaskGroup tasks=2 cancelling> is shutting down')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/quart/asgi.py", line 107, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/quart/asgi.py", line 142, in _send_response
    await send(
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/protocol/http_stream.py", line 200, in app_send
    await self._send_closed()
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/protocol/http_stream.py", line 247, in _send_closed
    await self.send(StreamClosed(stream_id=self.stream_id))
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/protocol/h2.py", line 230, in stream_send
    await self.send(Updated(idle=idle))
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/asyncio/tcp_server.py", line 90, in protocol_send
    await self.idle_task.restart(self._task_group, self._idle_timeout)
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/asyncio/worker_context.py", line 23, in restart
    self._handle = task_group._task_group.create_task(action())  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/taskgroup/taskgroups.py", line 147, in create_task
    raise RuntimeError(f"TaskGroup {self!r} is shutting down")
RuntimeError: TaskGroup <TaskGroup tasks=2 cancelling> is shutting down
```

and at a time I saw the one that I wrote in the issue report. 

I thought it was relevant, because no matter how I got this (because I absolute can't know, I only use the response and request, nothing else complicated) all needed I think is to add the `await` keyword line 141 in the ctx file. 

I don't have more elements, sorry.

**Comment by davidism** [comment]
> I am not sure what is exactly doing this issue.

You don't need to be, that's what we can figure out once we have an example that reproduces the issue.

> I only use the response and request

Show a minimal program that does that, and provide instructions for how to use it to produce the result you're getting. A minimal example makes it possible for us to see the issue and debug it.

**Comment by Kaki-In** [comment]
I got the same error like that : 

```
/usr/local/lib/python3.10/dist-packages/werkzeug/datastructures/headers.py:383: RuntimeWarning: coroutine 'TCPServer._idle_timeout' was never awaited
  self.set(key, value)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

at the line : 
```
result.headers['Access-Control-Allow-Origin'] = "something..."
```

if it can help

**Comment by Kaki-In** [comment]
I don't know exactly how to reproduce a small example, but what I do is that : 

1. When the client connects, if it does not have a cookie id, I create a new one
2. Then I execute something depending on what is needed (it should not come from there)
3. Then I set the cookie to save the id

If I am not wrong, the cookie should be got with : 
```python3
user_id = request.cookies.get('user_id')
```

and set with : 
```python3
response.set_cookie('user_id', user_id) # eventually domain=a.domain.name
```

Like that, GET is perfectly working but not POST, and so POST writes me a lot of errors, I can't understand why. 

Because I am using another port that the base website (I use quart to build an API), I am having a lot of issues with the CORS policy about the compatibility with cookies and so I set the header : 

```python3
await result.headers.add('Access-Control-Allow-Origin', "https://the.domain.name")
```

But when I do that I get a 400 error (if I comment the line, the result code is 200 but the browser cors refuses it). 

So after working a little maybe the problem comes from me, but the difference between GET and POST still make me wonder some questions

**Comment by Kaki-In** [comment]
Finally the 400 error came from `request.args['an_invalid_key']` so I don't think the 400 error is important. 

I think the better to do for the moment is that I will see exactly what I should do and come back when I will be sure about where do the issue comes from. 

Sorry for inconvenience

**Comment by Kaki-In** [comment]
Ok I am really really sorry, it seems that it came from me, I was having some issues treating the request args and data (args from GET and data for POST) and that made my API disfunction sometimes.
