### ISSUE TITLE
Error in await request.form

### ISSUE THREAD

**Issue by Yunexiz** [pallets/quart#366]
When using await request.form, an error occurs:
```196, in parse
    if field_size > self.max_form_memory_size:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

self.max_form_memory_size is None, although I have tried both explicitly setting it and letting it default.

I used 2 files, 1 file sent POST request form data to the erroring file which contains 1 item "inputText". The error immediately occurs at await request.form.

The erroring file should have returned a json response containing a list of dicts.

Environment:

- Python version: 3.12.6-bullseye
- Quart version: 0.19.7

**Comment by davidism** [comment]
Silly mistake, missing a check in the fix present in 0.19.7. Just released 0.19.8.
