### ISSUE TITLE
Type checking has been failing in CI for the last 6 months

### ISSUE THREAD

**Issue by JamesParrott** [pallets/quart#375]
Type checking doesn't pass when running tests for PRs

https://github.com/pallets/quart/actions/workflows/tests.yaml

https://github.com/pallets/quart/actions/runs/9331655216

**Comment by JamesParrott** [comment]
Hypercorn 0.17.0 added a "state" key (about 6 months ago) to 3 TypedDicts (*) used by Quart in testing type hints. This causes 11 of the 21 type check errors.

(*) HTTPScope, LifespanScope, WebsocketScope,

https://github.com/pgjones/hypercorn/blame/84d06b8cf47798d2df7722273341e720ec0ea102/src/hypercorn/typing.py#L58

Sticking plaster fix until someone figures out how to adjust the tests, pin hypercorn to <=0.16.0:

**Comment by JamesParrott** [comment]
It is necessary either to remove the concrete types from the now non-generic AiofilesContextManager in Quart, or pin aiofiles to <=23.2.1

aiofiles 24.1.0 changed the type annotation of AiofilesContextManager , making it no longer a Coroutine, no longer a generic type. 

[quart/src/quart/wrappers/response.py](https://github.com/pallets/quart/blob/ef23e8b063ee0b1ae95ba5828570552685ad89bb/src/quart/wrappers/response.py#L151)

Line 151 in [ef23e8b](https://github.com/pallets/quart/commit/ef23e8b063ee0b1ae95ba5828570552685ad89bb)
 self.file_manager: AiofilesContextManager[None, None, AsyncBufferedReader] = None 

"Switch to more modern async idioms: Remove types.coroutine and make AiofilesContextManager an awaitable instead a coroutine."
https://github.com/Tinche/aiofiles/releases/tag/v24.1.0

**Comment by JamesParrott** [comment]
AnyStr is deprecated in Python 3.13, and is being used incorrectly in any case (pretty much as per the example of incorrect usage in the docs https://docs.python.org/3/library/typing.html#typing.AnyStr).

https://github.com/pallets/quart/blob/ef23e8b063ee0b1ae95ba5828570552685ad89bb/src/quart/wrappers/response.py#L317

**Comment by JamesParrott** [comment]
Will be completed by PR #374

**Comment by pgjones** [comment]
Fixed now
