### ISSUE TITLE
Hypercorn 0.17.0 added a "state" key (about 6 months ago) to 3 TypedDicts (*) used by Quart in testing type hints.  This causes 11 of the 21 type check errors.

### ISSUE THREAD

**Issue by JamesParrott** [pallets/quart#376]
(*) HTTPScope, LifespanScope, WebsocketScope, 

https://github.com/pgjones/hypercorn/blame/84d06b8cf47798d2df7722273341e720ec0ea102/src/hypercorn/typing.py#L58

**Comment by davidism** [comment]
Please move this to #375
