### ISSUE TITLE
Updated version Flask, error 

### ISSUE THREAD

**Issue by DaniMunos95** [pallets/quart#382]
In the library requirements new versions of Flask are allowed, so 2 days ago a new version was released that generates the following error.
![image](https://github.com/user-attachments/assets/2bd0122f-b1c3-4bec-822e-f4a5176532b0)

To replicate this error, all you have to do is uninstall the Flask and Quart version and reinstall Quart and create an app.

Environment:

- Python version: 3.9
- Quart version: 0.19.6

**Comment by davidism** [comment]
Fixed in Quart 0.19.9.

Be sure to use a tool like pip-compile to pin your application's full dependency tree so you can have reproducible deployments and control when you get updates.
